window.test4 = function (o) {

  var obj = {
    tokenId: JSON.parse(o.cuserInfo).data.tokenId,
    secretKey: JSON.parse(o.cuserInfo).data.secretKey,
    cuserInfo: JSON.parse(o.cuserInfo).data.cuserInfo,
    firmInfo: JSON.parse(o.cuserInfo).data.firmInfo,
    system: JSON.parse(o.system).data,
  }
  console.log(JSON.stringify(obj));
  console.log(this);
  


//   var a = {
//     "tokenId": "21a82d0573b58db826e0bc7d7ebceaed",
//     "secretKey": "znf67jgqi89ptrkmvrz2g45tgnwxbgp",
//     "cuserInfo": {
//         "id": "1881",
//         "cuserId": "",
//         "mobile": "18315318515",
//         "idcard": "",
//         "realName": "朱1",
//         "petName": "",
//         "sex": 1,
//         "birthday": "",
//         "email": "",
//         "qq": "",
//         "password": "72ba0e8fec294213410e6988f3d77fb0",
//         "province": "32",
//         "city": "3201",
//         "regMethod": 1,
//         "regTime": "2017-04-01 19:38:19",
//         "note": "",
//         "sinaNum": "",
//         "faceImg": "",
//         "openId": "",
//         "uid": "",
//         "pwdQuestion": "",
//         "pwdAnswer": "",
//         "websiteNode": "",
//         "status": 1,
//         "firm": 132,
//         "isMain": 1,
//         "wxOpenId": ""
//     },
//     "firmInfo": {
//         "id": "132",
//         "firmName": "芜湖大飞",
//         "saleCard": "Xcf200833881",
//         "boss": "",
//         "linkMan": "芜湖大飞",
//         "linkTel": "18315318515",
//         "address": "浙江省杭州市华业大厦",
//         "idCard": "",
//         "dealNum": "",
//         "signMan": "",
//         "signTime": "2016-11-10",
//         "province": "33",
//         "city": "3301",
//         "county": "330108",
//         "websiteNode": "3301",
//         "createTime": "2016-04-15 15:39:26",
//         "note": "12",
//         "userGrade": "LV8",
//         "score": 1491740,
//         "authStatus": 1,
//         "status": 1,
//         "deliveryTime": "03:00-02:00",
//         "faceImgUrl": "zhangshuoinfo.b0.upaiyun.com/1543551521.gif",
//         "description": "",
//         "staffId": 12,
//         "liveness": "",
//         "latitude": "30.188747",
//         "longitude": "120.181104",
//         "firmFrom": 2,
//         "firmType": "SG",
//         "firstStaff": "",
//         "claimTime": "",
//         "isVisited": 1,
//         "firmLevel": "",
//         "doOper": "",
//         "reason": "",
//         "referrer": "",
//         "referrerId": "",
//         "cuserInfoList": [{
//             "id": "1880",
//             "cuserId": "",
//             "mobile": "18315318516",
//             "idcard": "",
//             "realName": "朱2",
//             "petName": "",
//             "sex": 1,
//             "birthday": "",
//             "email": "",
//             "qq": "",
//             "password": "8ae7602b01c7e3f97296567a6b78a478",
//             "province": "32",
//             "city": "3201",
//             "regMethod": 1,
//             "regTime": "2017-04-01 18:52:46",
//             "note": "",
//             "sinaNum": "",
//             "faceImg": "",
//             "openId": "",
//             "uid": "",
//             "pwdQuestion": "",
//             "pwdAnswer": "",
//             "websiteNode": "",
//             "status": 1,
//             "firm": 132,
//             "isMain": 2,
//             "wxOpenId": ""
//         }],
//         "street": "330108002",
//         "road": "",
//         "provinceName": "",
//         "cityName": "",
//         "countyName": "",
//         "staffName": "",
//         "websiteNodeName": "杭州站",
//         "flag": "",
//         "next": "",
//         "surplusScore": "",
//         "expand": 2,
//         "loc": {
//             "lon": 120.181104,
//             "lat": 30.188747
//         },
//         "exp": 5632.67,
//         "monthExp": 5632.67,
//         "vip": 1,
//         "vipGrade": 4,
//         "hasSendNewCoupon": ""
//     }
//   }
//   console.log(a);
  window.appInit(obj);
}
